---
classes:
  java.util.Comparator<T>:
    dev_mode: false
    doc_string: |
      \brief Comparator.
      \tparam T The type of element that this comparator compares.
    members:
    - type: method
      name: compare
      const: true
      virtual: true
      arguments:
      - name: x
        type:
          java: const T
      - name: y
        type:
          java: const T
      return:
        java: int
      doc_string: |
        \brief Compare \p x and \p y.
        \return An integer less than 0, if \p x comes before \p y.
        An integer greater than 0, if \p x comes after \p y.
        A zero value otherwise.
    - type: method
      name: naturalOrder
      static: true
      return:
        java: java.util.Comparator<T>
      body: |
        return ::java::cast<$boundTemplateType(java.("java.util.Comparator<java.lang.Object>"), "style=type, class")$>(
            $boundTemplateType(java.({java.util.Comparators\$NaturalOrderComparator}), "style=type, class")$::Instance());
    - type: method
      name: reversed
      const: true
      virtual: true
      return:
        java: const java.util.Comparator<T>
      body: |
        return $boundTemplateType(java.({java.util.Collections}), "style=type, class")$::reverseOrder($boundTemplateType(java.({const java.util.Comparator<T>}), "style=type, class")$(::java::_direct(), this->shared_from_this(this)));
