---
classes:
  java.util.NavigableMap<K, V>:
    members:
    - type: method
      name: begin
      virtual: true
      return:
        cxx: ::java::bidirectional_pair_iterator<$boundTemplateType(java.("K"), "style=type")$, $boundTemplateType(java.("V"), "style=type")$>
        includes:
          declaration:
          - java/iterator.h
    - type: method
      name: end
      virtual: true
      return:
        cxx: ::java::bidirectional_pair_iterator<$boundTemplateType(java.("K"), "style=type")$, $boundTemplateType(java.("V"), "style=type")$>
        includes:
          declaration:
          - java/iterator.h
    - type: method
      name: begin
      virtual: true
      const: true
      return:
        cxx: ::java::bidirectional_pair_iterator<const $boundTemplateType(java.("K"), "style=type")$, const $boundTemplateType(java.("V"), "style=type")$>
        includes:
          declaration:
          - java/iterator.h
    - type: method
      name: end
      virtual: true
      const: true
      return:
        cxx: ::java::bidirectional_pair_iterator<const $boundTemplateType(java.("K"), "style=type")$, const $boundTemplateType(java.("V"), "style=type")$>
        includes:
          declaration:
          - java/iterator.h
    - type: method
      name: find
      virtual: true
      const: true
      arguments:
      - name: k
        type:
          java: const K
      return:
        cxx: ::java::bidirectional_pair_iterator<const $boundTemplateType(java.({K}), "style=type")$, const $boundTemplateType(java.({V}), "style=type")$>
        includes:
          declaration:
          - java/iterator.h
      doc_string: |
        \brief Find element in the map.
        \param k Key to the element to find.
        \returns Iterator to the element, or if the element is absent, an iterator to end.
    - type: method
      name: find
      virtual: true
      arguments:
      - name: k
        type:
          java: const K
      return:
        cxx: ::java::bidirectional_pair_iterator<$boundTemplateType(java.({K}), "style=type")$, $boundTemplateType(java.({V}), "style=type")$>
        includes:
          declaration:
          - java/iterator.h
      doc_string: |
        \brief Find element in the set.
        \param k Key to the element to find.
        \returns Iterator to the element, or if the element is absent, an iterator to end.
    - type: method
      name: lower_bound
      override: true
      arguments:
      - name: k
        type:
          java: const K
      return:
        cxx: ::java::bidirectional_pair_iterator<$boundTemplateType(java.({K}), "style=type")$, $boundTemplateType(java.({V}), "style=type")$>
        includes:
          declaration:
          - java/iterator.h
      doc_string: |
        \brief Find element in the map.
        \param k Key to the element to find.
        \returns Iterator to the element with key greater than or equal to \p k.
    - type: method
      name: lower_bound
      const: true
      override: true
      arguments:
      - name: k
        type:
          java: const K
      return:
        cxx: ::java::bidirectional_pair_iterator<const $boundTemplateType(java.({K}), "style=type")$, const $boundTemplateType(java.({V}), "style=type")$>
        includes:
          declaration:
          - java/iterator.h
      doc_string: |
        \brief Find element in the map.
        \param k Key to the element to find.
        \returns Iterator to the element with key greater than or equal to \p k.
    - type: method
      name: upper_bound
      override: true
      arguments:
      - name: k
        type:
          java: const K
      return:
        cxx: ::java::bidirectional_pair_iterator<$boundTemplateType(java.({K}), "style=type")$, $boundTemplateType(java.({V}), "style=type")$>
        includes:
          declaration:
          - java/iterator.h
      doc_string: |
        \brief Find element in the map.
        \param k Key to the element to find.
        \returns Iterator to the element with key greater than \p k.
    - type: method
      name: upper_bound
      const: true
      override: true
      arguments:
      - name: k
        type:
          java: const K
      return:
        cxx: ::java::bidirectional_pair_iterator<const $boundTemplateType(java.({K}), "style=type")$, const $boundTemplateType(java.({V}), "style=type")$>
        includes:
          declaration:
          - java/iterator.h
      doc_string: |
        \brief Find element in the map.
        \param k Key to the element to find.
        \returns Iterator to the element with key greater than \p k.
    - type: method
      name: headMap
      virtual: true
      arguments:
      - name: toKey
        type:
          java: const K
      return:
        java: java.util.NavigableMap<K, V>
      body: |
        return headMap(toKey, false);
    - type: method
      name: headMap
      virtual: true
      const: true
      arguments:
      - name: toKey
        type:
          java: const K
      return:
        java: const java.util.NavigableMap<K, V>
      body: |
        return headMap(toKey, false);
    - type: method
      name: tailMap
      virtual: true
      arguments:
      - name: fromKey
        type:
          java: const K
      return:
        java: java.util.NavigableMap<K, V>
      body: |
        return tailMap(fromKey, true);
    - type: method
      name: tailMap
      virtual: true
      const: true
      arguments:
      - name: fromKey
        type:
          java: const K
      return:
        java: const java.util.NavigableMap<K, V>
      body: |
        return tailMap(fromKey, true);
    - type: method
      name: subMap
      virtual: true
      arguments:
      - name: fromKey
        type:
          java: const K
      - name: toKey
        type:
          java: const K
      return:
        java: java.util.NavigableMap<K, V>
      body: |
        return subMap(fromKey, true, toKey, false);
    - type: method
      name: subMap
      virtual: true
      const: true
      arguments:
      - name: fromKey
        type:
          java: const K
      - name: toKey
        type:
          java: const K
      return:
        java: const java.util.NavigableMap<K, V>
      body: |
        return subMap(fromKey, true, toKey, false);
    - type: method
      name: headMap
      virtual: true
      arguments:
      - name: toKey
        type:
          java: const K
      - name: toInclusive
        type:
          java: boolean
      return:
        java: java.util.NavigableMap<K, V>
    - type: method
      name: headMap
      virtual: true
      const: true
      arguments:
      - name: toKey
        type:
          java: const K
      - name: toInclusive
        type:
          java: boolean
      return:
        java: const java.util.NavigableMap<K, V>
    - type: method
      name: tailMap
      virtual: true
      arguments:
      - name: fromKey
        type:
          java: const K
      - name: fromInclusive
        type:
          java: boolean
      return:
        java: java.util.NavigableMap<K, V>
    - type: method
      name: tailMap
      virtual: true
      const: true
      arguments:
      - name: fromKey
        type:
          java: const K
      - name: fromInclusive
        type:
          java: boolean
      return:
        java: const java.util.NavigableMap<K, V>
    - type: method
      name: subMap
      virtual: true
      arguments:
      - name: fromKey
        type:
          java: const K
      - name: fromInclusive
        type:
          java: boolean
      - name: toKey
        type:
          java: const K
      - name: toInclusive
        type:
          java: boolean
      return:
        java: java.util.NavigableMap<K, V>
    - type: method
      name: subMap
      virtual: true
      const: true
      arguments:
      - name: fromKey
        type:
          java: const K
      - name: fromInclusive
        type:
          java: boolean
      - name: toKey
        type:
          java: const K
      - name: toInclusive
        type:
          java: boolean
      return:
        java: const java.util.NavigableMap<K, V>
    - type: method
      name: descendingMap
      virtual: true
      return:
        java: java.util.NavigableMap<K, V>
      doc_string: |
        \brief Create a view of this map, with reversed ordering.
    - type: method
      name: descendingMap
      virtual: true
      const: true
      return:
        java: const java.util.NavigableMap<K, V>
      doc_string: |
        \brief Create a view of this map, with reversed ordering.
