---
classes:
  java.util.Queue<E>:
    dev_mode: false
    members:
    - type: method
      name: push
      virtual: true
      return:
        cxx: void
      arguments:
      - name: e
        type:
          java: E
      doc_string: |
        \brief Pushes the element \p e on the end of the queue.
        \param e The element to be pushed onto the queue.
    - type: method
      name: pop
      virtual: true
      return:
        cxx: void
      doc_string: |
        \brief Removes an element from the front of the queue.
    - type: method
      name: front
      virtual: true
      const: true
      return:
        java: const E
      doc_string: |
        \brief Retrieve the first element from the queue.
        \returns The first element.
    - type: method
      name: back
      virtual: true
      const: true
      return:
        java: const E
      doc_string: |
        \brief Retrieve the last element from the queue.
        \returns The last element.
    - type: method
      name: front
      virtual: true
      return:
        java: E
      doc_string: |
        \brief Retrieve the first element from the queue.
        \returns The first element.
    - type: method
      name: back
      virtual: true
      return:
        java: E
      doc_string: |
        \brief Retrieve the last element from the queue.
        \returns The last element.
    - type: method
      name: insert
      override: true
      arguments:
      - name: e
        type:
          java: E
      body: |
        push(std::move(e));
      doc_string: |
        \brief Add an element to the end of the list.
