---
classes:
  java.lang.AbstractMethodError:
    dev_mode: false
    doc_string: |
      \brief JVM errors.
      \details
      Indicates an abstract method was called.
    inherit_constructors: true
