---
classes:
  java.lang.ArithmeticException:
    dev_mode: false
    doc_string: |
      \brief Exception for arithmatic errors.
      \details Thrown by java on for instance, divide by zero.
    inherit_constructors: true
