---
classes:
  java.lang.ArrayStoreException:
    dev_mode: false
    doc_string: |
      \brief Exception indicating an attempt was made to store the wrong type in an array.
    inherit_constructors: true
