---
classes:
  java.lang.CharSequence:
    dev_mode: false
    doc_string: |
      \brief Character sequence.
      \details Holds a sequence of characters.

      \attention
      Java uses UTF-16, but in C++ we use UTF-8.
      Therefore our string are UTF-8 sequences and length/index computation is based on 8 bit characters.
    members:
    - type: method
      name: length
      const: true
      noexcept: true
      return:
        cxx: ::std::size_t
        includes:
          declaration:
          - cstddef
      body: |
        return size();
      doc_string: |
        \brief Retrieve the size of the string.
        \returns The number of characters in the string.
    - type: method
      name: size
      virtual: true
      const: true
      noexcept: true
      covariant_return: false
      return:
        cxx: ::std::size_t
        includes:
          declaration:
          - cstddef
      doc_string: |
        \brief Retrieve the size of the string.
        \returns The number of characters in the string.
    - type: method
      name: empty
      virtual: true
      const: true
      noexcept: true
      covariant_return: false
      return:
        cxx: bool
      doc_string: |
        \brief Test if this is an empty string.
        \returns True if the string is empty. False otherwise.
      body: |
        return size() == 0u;
    - type: method
      name: at
      virtual: true
      const: true
      arguments:
      - name: index
        type:
          cxx: ::std::size_t
          includes:
            declaration:
            - cstddef
      return:
        cxx: char
      doc_string: |
        \brief Retrieve the character at the given index from the list.
        \param index Index of the character to be returned.
        \returns Character at the given index.
        \throws std::out_of_range if the index exceeds the string size.
    - type: method
      name: front
      virtual: true
      const: true
      return:
        cxx: char
      doc_string: |
        \brief Front of the string.
        \returns First character of the string.
    - type: method
      name: back
      virtual: true
      const: true
      return:
        cxx: char
      doc_string: |
        \brief Back of the string.
        \returns Last character of the string.
    - type: method
      name: substr
      virtual: true
      const: true
      arguments:
      - name: pos
        type:
          cxx: ::std::size_t
          includes:
            declaration:
            - cstddef
      return:
        java: java.lang.String
      doc_string: |
        \brief Retrieve a substring.
        \details: Returns the substring starting at \p pos.
        \param pos Starting index for the substring.
        \return String containing everything from \p pos until the end.
        \throws std::out_of_range if \p pos larger than `size()`.
      body: |
        return substr(pos, std::size_t(-1));
    - type: method
      name: substr
      virtual: true
      const: true
      arguments:
      - name: pos
        type:
          cxx: ::std::size_t
          includes:
            declaration:
            - cstddef
      - name: count
        type:
          cxx: ::std::size_t
          includes:
            declaration:
            - cstddef
      return:
        java: java.lang.String
      doc_string: |
        \brief Retrieve a substring.
        \details: Returns the substring starting at \p pos.
        The substring will be at most \p count characters.
        \param pos Starting index for the substring.
        \param count Number of characters to include in the returned string.
        \return String containing up to \p count characters starting at \p pos.
        \throws std::out_of_range if \p pos larger than `size()`.
    - type: method
      name: str
      virtual: true
      const: true
      return:
        cxx: ::std::string
        includes:
          declaration:
          - string
    - type: method
      name: subSequence
      virtual: true
      const: true
      arguments:
      - name: pos
        type:
          cxx: ::std::size_t
          includes:
            declaration:
            - cstddef
      return:
        java: java.lang.CharSequence
      doc_string: |
        \brief Retrieve a substring.
        \details: Returns the substring starting at \p pos.
        \param pos Starting index for the substring.
        \return CharSequence containing everything from \p pos until the end.
        \throws std::out_of_range if \p pos larger than `size()`.
      body: |
        return subSequence(pos, std::size_t(-1));
    - type: method
      name: subSequence
      virtual: true
      const: true
      arguments:
      - name: pos
        type:
          cxx: ::std::size_t
          includes:
            declaration:
            - cstddef
      - name: count
        type:
          cxx: ::std::size_t
          includes:
            declaration:
            - cstddef
      return:
        java: java.lang.CharSequence
      doc_string: |
        \brief Retrieve a substring.
        \details: Returns the substring starting at \p pos.
        The substring will be at most \p count characters.
        \param pos Starting index for the substring.
        \param count Number of characters to include in the returned string.
        \return CharSequence containing up to \p count characters starting at \p pos.
        \throws std::out_of_range if \p pos larger than `size()`.
