---
classes:
  java.lang.Character:
    dev_mode: false
#    var_type:
#      java: char
    fields:
      value:
        const: true
        default: 0
    members:
    - type: constructor
      arguments:
      - name: v
        type:
          java: char
      initializers:
        value: v
    - type: method
      name: compareTo
      const: true
      override: true
      arguments:
      - name: o
        type:
          java: const java.lang.Character
      return:
        java: int
      body: |
        $boundTemplateType(java.({const char}), "style=type, class")$ x = value;
        $boundTemplateType(java.({const char}), "style=type, class")$ y = o->value();

        if (x == y) return 0;
        return (x < y ? -1 : 1);
