---
classes:
  java.lang.CloneNotSupportedException:
    dev_mode: false
    doc_string: |
      \brief Exception indicating the clone function is not supported.
      \details
      In java, the clone method is provided by the JVM and creates a shallow copy.
      It exists in every class, but will refuse to operate unless the object implements the Cloneable interface.
      Refusal is signified by this exception.
    inherit_constructors: true
