---
classes:
  java.lang.Double:
    dev_mode: false
#    var_type:
#      java: double
    fields:
      value:
        const: true
        default: 0
    members:
    - type: constructor
      arguments:
      - name: v
        type:
          java: double
      initializers:
        value: v
    - type: method
      name: compareTo
      const: true
      override: true
      arguments:
      - name: o
        type:
          java: const java.lang.Double
      return:
        java: int
      body: |
        $boundTemplateType(java.({const double}), "style=type, class")$ x = value;
        $boundTemplateType(java.({const double}), "style=type, class")$ y = o->value();

        if (x == y) return 0;
        return (x < y ? -1 : 1);
    - type: method
      name: longValue
      override: true
      const: true
      return:
        java: long
      body: |
        return value;
    - type: method
      name: doubleValue
      override: true
      const: true
      return:
        java: double
      body: |
        return value;
