---
classes:
  java.lang.EnumConstantNotPresentException:
    dev_mode: false
    doc_string: |
      \brief Exception indicating an array index is out of range.
    members:
    - type: constructor
      arguments:
      - name: enumType
        type:
          java: java.lang.Class<? extends java.lang.Enum<?>>
      - name: constantName
        type:
          java: java.lang.String
      super: $boundTemplateType(java.({java.lang.String}), "style=type, class")$(::java::allocate, enumType->name() + u8"." + constantName->value())
      initializers:
        enumType: ::std::move(enumType)
        constantName: ::std::move(constantName)
      includes:
        implementation:
        - utility
