---
classes:
  java.lang.Error:
    dev_mode: false
    doc_string: |
      \brief JVM errors.
      \details
      This indicates a problem in the virtual machine.
      They are always unchecked.
    inherit_constructors: true
