---
classes:
  java.lang.RuntimeException:
    dev_mode: false
    doc_string: |
      \brief Unchecked exception.
    members:
    - type: constructor
    - type: constructor
      arguments:
      - name: cause
        type:
          java: java.lang.Throwable
      super: ::std::move(cause)
    - type: constructor
      arguments:
      - name: message
        type:
          java: java.lang.String
      super: ::std::move(message)
    - type: constructor
      arguments:
      - name: message
        type:
          java: java.lang.String
      - name: cause
        type:
          java: java.lang.Throwable
      super: ::std::move(message), ::std::move(cause)
