---
classes:
  java.lang.InstantiationException:
    dev_mode: false
    doc_string: |
      \brief Exception indicating the new operator was called on an abstract class or interface, an array class, a primitive class, or void.
    inherit_constructors: true
