---
classes:
  java.lang.LinkageError:
    dev_mode: false
    doc_string: |
      \brief JVM errors.
      \details
      This indicates a class has changed in a way that is incompatible with its use.
    inherit_constructors: true
