---
classes:
  java.lang.NegativeArraySizeException:
    dev_mode: false
    doc_string: |
      \brief Exception thrown when an attempt is made to create an array with a negative size.
    inherit_constructors: true
