---
classes:
  java.util.function.BiPredicate<X, Y>:
    dev_mode: false
    doc_string: |
      \brief Predicate that accepts 2 arguments.
    members:
    - type: method
      name: test
      virtual: true
      arguments:
      - name: x
        type:
          java: X
      - name: y
        type:
          java: Y
      return:
        java: boolean
