---
classes:
  java.util.function.DoubleBinaryOperator:
    dev_mode: false
    doc_string: |
      \brief Operator that accept two double arguments and returns a double result.
    members:
    - type: method
      name: applyAsDouble
      virtual: true
      arguments:
      - name: x
        type:
          java: double
      - name: y
        type:
          java: double
      return:
        java: double
