---
classes:
  java.util.function.DoubleToLongFunction:
    dev_mode: false
    doc_string: |
      \brief Function that accepts a double argument and returns a long int.
    members:
    - type: method
      name: applyAsLong
      virtual: true
      arguments:
      - name: x
        type:
          java: double
      return:
        java: long
