---
classes:
  java.util.function.Function<X, R>:
    dev_mode: false
    doc_string: |
      \brief Function that accepts one argument and returns a result.
    members:
    - type: method
      name: apply
      virtual: true
      arguments:
      - name: x
        type:
          java: X
      return:
        java: R
