---
classes:
  java.util.function.IntFunction<R>:
    dev_mode: false
    doc_string: |
      \brief Functor that accepts 1 argument and returns a result.
    members:
    - type: method
      name: apply
      virtual: true
      arguments:
      - name: x
        type:
          java: int
      return:
        java: R
