---
classes:
  java.util.function.IntToLongFunction:
    dev_mode: false
    doc_string: |
      \brief Function that accepts an integer argument and returns a long int.
    members:
    - type: method
      name: applyAsLong
      virtual: true
      arguments:
      - name: x
        type:
          java: int
      return:
        java: long
