---
classes:
  java.util.function.LongPredicate:
    dev_mode: false
    doc_string: |
      \brief Functor that accepts 1 argument and returns a result.
    members:
    - type: method
      name: test
      virtual: true
      arguments:
      - name: x
        type:
          java: long
      return:
        java: boolean
