---
classes:
  java.util.function.LongConsumer:
    dev_mode: false
    doc_string: |
      \brief Functor that accepts 1 argument.
    members:
    - type: method
      name: accept
      virtual: true
      arguments:
      - name: x
        type:
          java: long
