---
classes:
  java.util.function.Predicate<X>:
    dev_mode: false
    doc_string: |
      \brief A predicate.
    members:
    - type: method
      name: test
      virtual: true
      arguments:
      - name: x
        type:
          java: X
      return:
        java: boolean
