---
classes:
  java.util.function.ToIntBiFunction<X, Y>:
    dev_mode: false
    doc_string: |
      \brief Function that accepts two arguments and returns an integer.
    members:
    - type: method
      name: applyAsInt
      virtual: true
      arguments:
      - name: x
        type:
          java: X
      - name: y
        type:
          java: Y
      return:
        java: int
