---
classes:
  java.util.function.ToIntFunction<X>:
    dev_mode: false
    doc_string: |
      \brief Function that accepts an argument and returns an integer.
    members:
    - type: method
      name: applyAsInt
      virtual: true
      arguments:
      - name: x
        type:
          java: X
      return:
        java: int
