---
classes:
  java.util.function.ToLongBiFunction<X, Y>:
    dev_mode: false
    doc_string: |
      \brief Function that accepts two arguments and returns a long integer.
    members:
    - type: method
      name: applyAsLong
      virtual: true
      arguments:
      - name: x
        type:
          java: X
      - name: y
        type:
          java: Y
      return:
        java: long
