---
scan:
  include:
  - java
  - java.lang
  - javax
  exclude:
  - java.applet
  - java.awt
  - java.beans
  - javax.activation
  - javax.activity
  - javax.crypto
  - javax.imageio
  - javax.jws
  - javax.management.remote.rmi
  - javax.naming
  - javax.print
  - javax.script
  - javax.security
  - javax.smartcardio
  - javax.sound
  - javax.sql
  - javax.swing
  - javax.rmi.CORBA
  - javax.rmi.CORBA_2_3
  - javax.tools
  - javax.transaction
  - javax.xml
classes:
  java.io.Serializable:
  java.lang.String:
    var_type:
      cxx: ::std::string
      includes:
        declaration:
        - string
    fields:
      value:
        doc_string: |
          \brief Contents of `java.lang.String`.
        type:
          cxx: ::std::string
          includes:
            declaration:
            - string
  java.lang.Class<Type>:
    final: false
    fields:
      dummySyntheticFieldForTestingTheCodeGenerator:
        final: false
        visibility: private
        doc_string: |
          \brief This field serves no purpose.
          \details I just wanted a synthetic field, to test that configuration fields end up correctly in the emitted code.
        type:
          java: java.lang.Object
    members:
    - type: method
      name: foobar
      return:
        java: java.lang.Class<java.lang.CharSequence>
      arguments:
      - name: x
        type:
          cxx: int
      - name: y
        type:
          java: java.lang.Integer
      includes:
        declaration:
        - string
      body: |
        return "foobar";
      visibility: public
