---
scan:
  include:
  - java
  - java.lang
  - javax
  exclude:
  - java.applet
  - java.awt
  - java.beans
  - javax.activation
  - javax.activity
  - javax.crypto
  - javax.imageio
  - javax.jws
  - javax.management.remote.rmi
  - javax.naming
  - javax.print
  - javax.script
  - javax.security
  - javax.smartcardio
  - javax.sound
  - javax.sql
  - javax.swing
  - javax.rmi.CORBA
  - javax.rmi.CORBA_2_3
  - javax.tools
  - javax.transaction
  - javax.xml
classes:
  java.io.Serializable:
  java.lang.String:
    var_type:
      cxx: ::std::string
      includes:
        declaration:
        - string
    fields:
      value:
        doc_string: |
          \brief Contents of `java.lang.String`.
          \note
          This field is const, so that shared instances of string don't affect eachother.
          This corresponds to the immutable property of java strings.
        const: true
        type:
          cxx: ::std::string
          includes:
            declaration:
            - string
    members:
    - type: constructor
      arguments:
      - name: s
        type:
          cxx: ::std::string_view
          includes:
            declaration:
            - string_view
            implementation:
            - string_view
      initializers:
        value: s.data(), s.size()
  java.lang.Class<Type>:
