---
scan:
  include:
  - java
  - java.lang
  - javax
  exclude:
  - java.applet
  - java.awt
  - java.beans
  - javax.activation
  - javax.activity
  - javax.crypto
  - javax.imageio
  - javax.jws
  - javax.management.remote.rmi
  - javax.naming
  - javax.print
  - javax.script
  - javax.security
  - javax.smartcardio
  - javax.sound
  - javax.sql
  - javax.swing
  - javax.rmi.CORBA
  - javax.rmi.CORBA_2_3
  - javax.tools
  - javax.transaction
  - javax.xml
classes:
  java.lang.Boolean:
    fields:
      value:
        const: true
    members:
    - type: constructor
      arguments:
      - name: v
        type:
          cxx: ::java::boolean_t
          includes:
            declaration:
            - java/primitives.h
      initializers:
        value: v
  java.lang.Character:
    fields:
      value:
        const: true
    members:
    - type: constructor
      arguments:
      - name: v
        type:
          cxx: ::java::char_t
          includes:
            declaration:
            - java/primitives.h
      initializers:
        value: v
  java.lang.Byte:
    fields:
      value:
        const: true
    members:
    - type: constructor
      arguments:
      - name: v
        type:
          cxx: ::java::byte_t
          includes:
            declaration:
            - java/primitives.h
      initializers:
        value: v
  java.lang.Short:
    fields:
      value:
        const: true
    members:
    - type: constructor
      arguments:
      - name: v
        type:
          cxx: ::java::short_t
          includes:
            declaration:
            - java/primitives.h
      initializers:
        value: v
  java.lang.Integer:
    fields:
      value:
        const: true
    members:
    - type: constructor
      arguments:
      - name: v
        type:
          cxx: ::java::int_t
          includes:
            declaration:
            - java/primitives.h
      initializers:
        value: v
  java.lang.Long:
    fields:
      value:
        const: true
    members:
    - type: constructor
      arguments:
      - name: v
        type:
          cxx: ::java::long_t
          includes:
            declaration:
            - java/primitives.h
      initializers:
        value: v
  java.lang.Float:
    fields:
      value:
        const: true
    members:
    - type: constructor
      arguments:
      - name: v
        type:
          cxx: ::java::float_t
          includes:
            declaration:
            - java/primitives.h
      initializers:
        value: v
  java.lang.Double:
    fields:
      value:
        const: true
    members:
    - type: constructor
      arguments:
      - name: v
        type:
          cxx: ::java::double_t
          includes:
            declaration:
            - java/primitives.h
      initializers:
        value: v
  java.io.Serializable:
    friends:
    - cxx: ::java::serialization::cycle_handler
      includes:
        declaration:
        - java/serialization/type_def_fwd.h
    members:
    - type: method
      name: do_encode_
      visibility: private
      virtual: true
      const: true
      return:
        cxx: ::cycle_ptr::cycle_gptr<::java::serialization::stream::stream_element>
      arguments:
      - name: hander_
        type:
          cxx: ::java::serialization::cycle_handler&
      includes:
        declaration:
        - java/serialization/encdec.h
        - cycle_ptr/cycle_ptr.h
        - java/serialization/type_def_fwd.h
        implementation:
        - java/serialization/type_def.h
      body: |
        return nullptr; // XXX erase body once rules take care of most things.
  java.lang.String:
    var_type:
      cxx: ::std::string
      includes:
        declaration:
        - string
    fields:
      value:
        doc_string: |
          \brief Contents of `java.lang.String`.
          \note
          This field is const, so that shared instances of string don't affect eachother.
          This corresponds to the immutable property of java strings.
        const: true
        type:
          cxx: ::std::string
          includes:
            declaration:
            - string
    members:
    - type: constructor
      arguments:
      - name: s
        type:
          cxx: ::std::string_view
          includes:
            declaration:
            - string_view
            implementation:
            - string_view
      initializers:
        value: s.data(), s.size()
    - type: method
      name: do_encode_
      visibility: private
      override: true
      final: true
      const: true
      return:
        cxx: ::cycle_ptr::cycle_gptr<::java::serialization::stream::stream_element>
      arguments:
      - name: hander_
        type:
          cxx: ::java::serialization::cycle_handler&
      body: |
        using namespace ::java::serialization::stream;
        using conversion_type = ::std::wstring_convert<
            std::codecvt_utf8_utf16<char16_t>,
            char16_t>;

        conversion_type conversion;

        // Note: No invocation of super.do_encode_,
        // because strings are special case encoded.
        return ::cycle_ptr::make_cycle<stream_string>(conversion.from_bytes(value.data(), value.data() + value.size()));
      includes:
        declaration:
        - java/serialization/type_def_fwd.h
        - java/serialization/encdec.h
        - cycle_ptr/cycle_ptr.h
        implementation:
        - java/serialization/encdec.h
        - cycle_ptr/cycle_ptr.h
        - locale
        - codecvt
        - java/serialization/type_def.h
  java.lang.Class<Type>:
    members:
    - type: method
      name: syntheticTestDummy
      return:
        java: java.lang.Class<Type[]>
      body: |
        return nullptr;
  java.util.Collection<E>:
    members:
    - type: method
      name: empty
      virtual: true
      const: true
      noexcept: true
      return:
        cxx: bool
    - type: method
      name: size
      virtual: true
      const: true
      noexcept: true
      return:
        cxx: ::std::size_t
        includes:
          declaration:
          - cstddef
    - type: method
      name: push_back
      virtual: true
      return:
        cxx: bool
      arguments:
      - name: e
        type:
          java: E
    - type: method
      name: pop_back
      virtual: true
      return:
        java: E
    - type: method
      name: clear
      virtual: true
      noexcept: true
  java.util.ArrayList<E>:
    members:
    - type: method
      name: empty
      override: true
      const: true
      noexcept: true
      return:
        cxx: bool
      body: |
        return data_.empty();
    - type: method
      name: size
      override: true
      const: true
      noexcept: true
      return:
        cxx: ::std::size_t
        includes:
          declaration:
          - cstddef
      body: |
        return data_.size();
    - type: method
      name: push_back
      override: true
      return:
        cxx: bool
      arguments:
      - name: e
        type:
          java: E
      body: |
        data_.push_back(std::move(e));
        return true;
    - type: method
      name: pop_back
      override: true
      return:
        java: E
      body: |
        $boundTemplateType(java.("E"), "style=type, class")$ r = std::move(data_.back());
        data_.pop_back();
        return r;
    - type: method
      name: clear
      override: true
      noexcept: true
      body: |
        data_.clear();
    fields:
      size:
        visibility: private
        rename: xxx_implement_remove_
      data_:
        visibility: private
        type:
          cxx: ::std::vector<$boundTemplateType(java.("E"), "style=type, class")$, ::cycle_ptr::cycle_allocator<::std::allocator<$boundTemplateType(java.("E"), "style=type, class")$>>>
          includes:
            declaration:
            - vector
            - cycle_ptr/allocator.h
        default: ::cycle_ptr::cycle_allocator<::std::allocator<$boundTemplateType(java.("E"), "style=type, class")$>>(*this)
